### ISSUE TITLE
Implement app-level helper classes

### ISSUE THREAD

**Issue by ppmag** [assaabloy-ppi/salt-channel-python#6]
For high-level use cases need to hide all implementation details of SaltChannel from user, exposing only AppChannel as a stream:

Implement two classes:
* class SaltChannelClientProtocol(asyncio.Protocol):
* class SaltChannelServerProtocol(asyncio.Protocol):
* Usage demo of two above

See examples:
https://docs.python.org/3/library/asyncio-protocol.html#tcp-echo-client-protocol
https://docs.python.org/3/library/asyncio-protocol.html#tcp-echo-server-protocol
https://pymotw.com/3/asyncio/io_protocol.html
https://github.com/eliben/python3-samples/blob/master/async/asyncio-len-prefixed-string-protocol.py

**Comment by franslundberg** [comment]
No update for long, closing it.
